## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [1]:
#Do your imports here
import numpy as np

![title](./img/3_2.png)
![title](./img/3_3.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [2]:
# okay numpy is great but... how would you inverse a matrix by hand?
A= np.array([[3,1,2],[-5,4,1],[0,3,-8]])
B = np.array([[0,5,-1],[3,2,-1],[10,0.5,4]])
# print(A.dot(B))
res =np.array([])
sol=np.array([])
total = 0
total1 = 0
for i in range(A.shape[0]):
    k=0
    while k < A.shape[0]:
          for j in range(B.shape[0]):
                total =total+(A[i,j]*B[j,k]) 
                total1 =total1+(B[i,j]*A[j,k]) 
          res = np.append(res, np.array([total]))
          sol = np.append(res, np.array([total1]))
          total = 0
          total1 = 0
          k+= 1

C =res.reshape(A.shape[0],B.shape[1])
C_ =res.reshape(B.shape[0],A.shape[1])
print("c23 =",C[1,2], '\n' ,"c23 =",C_[1,2]) 

print(C.shape[0],C.shape[1])
  
# def inverse_matrix(A):
#     return ""

c23 = 5.0 
 c23 = 5.0
3 3


In [3]:
# Using Numpy
A= np.array([[3,1,2],[-5,4,1],[0,3,-8]])
B = np.array([[0,5,-1],[3,2,-1],[10,0.5,4]])
# C =A.dot(B)
C =np.linalg.solve(A,B)
print(C)

[[ 0.16        0.86        0.04      ]
 [ 1.15428571  1.45428571 -0.06857143]
 [-0.81714286  0.48285714 -0.52571429]]


In [4]:
# Inverse matrix using numpy
def inverse_matrix(A):
    
    return np.linalg.inv(A)
a = np.array([[1,2],[2,3]])
A = np.array([[3,1,2],[-5,4,1],[0,3,-8]])
b= inverse_matrix(a)
# B = inverse_matrix(A)
c = b.dot(a)
# print(B)
# c=a.dot(b)
print(c)

[[1. 0.]
 [0. 1.]]


![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [5]:
# Just answer using code --> easy stuff!
A = np.array([[3, 0.6, 4, -3],[-1.3,4,0,8.6],[7,0,-8,0.006]])
B = np.array([[3, -5.76, 45, 0],[2, -2, 1.3 , 9],[-9, 0,0,0]])
C = np.array([[0,1009, -66.7849, 90],[0,5,4,-0.07],[-7.7,0,0,0]])

D =A+B-C
print(D[1,2],D[2,0])
# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed. 

-2.7 5.7


![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?

In [6]:
#  manually to solve with python
A= np.array([0.6,-15, 2, 5, 98])
B = np.array([[2,2,-4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]])

res =np.array([])

total = 0

# for i in range(A.ndim):
k=0
while k < B.shape[1]:
          for j in range(B.shape[0]):
                total =total+(A[j]*B[j,k]) 

          res = np.append(res, np.array([total]))

          total = 0
          k+= 1

C =res.reshape(A.ndim,B.shape[1])
print("c13 =",C[:,2]) 
print("Rows in C =",C.shape[0],"Columns in C=",C.shape[1])

  

c13 = [595.6]
Rows in C = 1 Columns in C= 3


In [7]:
# using numpy
A= np.array([0.6,-15, 2, 5, 98])
B = np.array([[2,2,-4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]])

C=A.dot(B)

print(C[2])

595.6
